language: node_js
os:
  - linux
dist: xenial
node_js:
  - stable
script:
  - npm run build
deploy:
  - provider: pages
    strategy: git
    'on':
      branch:
        - master
    local_dir: dist
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
